### ISSUE TITLE
DateTime in expression mapping 

### ISSUE THREAD

**Issue by mward-smartway2** [AutoMapper/AutoMapper.Extensions.ExpressionMapping#102]
public IEnumerable<TDto> Get(Expression<Func<TDto, bool>> lambda, string includes = "", Func<IQueryable<TDto>, IOrderedQueryable<TDto>> orderBy = null, int? skip = null, int? take = null)
		{
			var orderByFunc = Mapper.Map<Func<IQueryable<TRepository>, IOrderedQueryable<TRepository>>>(orderBy);
			var lambdaFunc = Mapper.MapExpression<Expression<Func<TRepository, bool>>>(lambda);
			var list = Repository.Get(lambdaFunc, includes, orderByFunc, skip, take);
			return Mapper.Map<IEnumerable<TDto>>(list);
		}

when lambda is x => x.SomeDateTime >= SomeOtherDateTime
MapExpression modifies the types correctly but leaves lambdaFunc as x => x.SomeDateTime >= const DateTime(string)

which cannot be used in a LInq to SQL expression by the Repository.

This problem does not exist in version 9.0 with ExpressionMapping 3.1.2 only in 10.0 with ExpresionMapping 4.

**Comment by BlaiseD** [comment]
Please post a sample we can run and see the unexpected results.

Show today's generated expression and the expression from the earlier release (which works against your database).

**Comment by mward-smartway2** [comment]
[AutoMapperIssue.zip](https://github.com/AutoMapper/AutoMapper.Extensions.ExpressionMapping/files/5635673/AutoMapperIssue.zip)

Isolated Sample attached

**Comment by BlaiseD** [comment]
The sample doesn't show where it fails - maybe add a [repo](https://github.com/mward-smartway2?tab=repositories) showing the exception - pretty sure that works against EF Core (without the `value(MyType).Date` expression).

The code you want to look at is [here](https://github.com/AutoMapper/AutoMapper.Extensions.ExpressionMapping/blob/9f1dc0909b97f6420d63035d6c2df7243fcb8b73/src/AutoMapper.Extensions.ExpressionMapping/XpressionMapperVisitor.cs#L60) - if it is indeed failing.

**Comment by mward-smartway2** [comment]
[AutoMapperIssue.zip](https://github.com/AutoMapper/AutoMapper.Extensions.ExpressionMapping/files/5636933/AutoMapperIssue.zip)

I have added code which shows the Exception

**Comment by BlaiseD** [comment]
The sample does not show an exception related to this library.

[This test in the OData Extensions library](https://github.com/AutoMapper/AutoMapper.Extensions.OData/blob/6224f587b1f61a4a750593f0945a2824496bea31/AutoMapper.OData.EFCore.Tests/GetQueryTests.cs#L102) maps date constants in a filter expression (using this library).

**Comment by mward-smartway2** [comment]
I did't say that the exception was in this Library, merely that the exression was modified in such a way as  make it unusable in EFCore 3.1 with Microsoft.Data.SqlClient.

**Comment by mward-smartway2** [comment]
It also fails with Microsoft.EntityFrameworkCore.SqlServer 5.0
