### ISSUE TITLE
Mapping entities with ValueObject field

### ISSUE THREAD

**Issue by DenisNP** [AutoMapper/AutoMapper.Extensions.ExpressionMapping#112]
I have a business logic object `User` with ValueObject field `UserId`. I need to translate expression tree with `User` to similar tree with `DbUser` using AutoMapper.

**Here is my setup:**
```cs
public static void Main(string[] args)
{
	// create new AutoMapper
	var mapperConfiguration = new MapperConfiguration(
		cfg =>
		{
			cfg.CreateMap<UserId, string>().ConvertUsing(u => u.ToString());
			cfg.CreateMap<string, UserId>().ConvertUsing(u => UserId.FromString(u));
			cfg.CreateMap<User, DbUser>()
				.ForMember(dbu => dbu.Id, opt => opt.MapFrom(u => u.Id.ToString()));
			cfg.CreateMap<DbUser, User>()
				.ForMember(u => u.Id, opt => opt.MapFrom(dbu => UserId.FromString(dbu.Id)));

			cfg.AddExpressionMapping();
		}
	);

	mapperConfiguration.AssertConfigurationIsValid();
	IMapper mapper = mapperConfiguration.CreateMapper();

	// map some expression
	var idToFind = new UserId(Guid.NewGuid());
	Expression<Func<User, bool>> bllExpression = x => x.Id == idToFind;

	var dbExpression = mapper.MapExpression<Expression<Func<DbUser, bool>>>(bllExpression);
	Console.WriteLine(dbExpression.ToString());
}
```

**User and DbUser:**
```cs
public class User
{
    public UserId Id { get; set; }
    public string Name { get; set; }
}

public class DbUser
{
    public string Id { get; set; }
    public string Name { get; set; }
}
```
**UserId:**
```cs
public class UserId
{
	public Guid Id { get; }

	public UserId(Guid id) => Id = id;

	public override string ToString()
	{
		return Id.ToString();
	}

	public static UserId FromString(string value)
	{
		return new UserId(Guid.Parse(value));
	}

	public static bool operator ==(UserId a, UserId b)
	{
		return a?.Id == b?.Id;
	}

	public static bool operator !=(UserId a, UserId b)
	{
		return a?.Id != b?.Id;
	}
}
```

So, when I convert those expressions I get this result:

`x => (FromString(x.Id) == 799e50f4-339f-4207-819e-194bbe206ae2)`

But I cannot use this expression as database query e.g. in EntityFramework or MongoDb. Because there is no `FromString` function. Instead I need to compare already flattened values, in this case `string`:

`x => (x.Id == "799e50f4-339f-4207-819e-194bbe206ae2")`

How can I get this expression?

[Link to .NET Fiddle][1]

  [1]: https://dotnetfiddle.net/L5dvJZ

**Comment by BlaiseD** [comment]
If expression mapping works then it's not an issue with this library.

SQL Server is limited even with `Guid` or `Enum` types - see issue #64.  You're sending it a class called `UserId`.  You'll want to simplify the query so SQL Server can process it.  

Something like:
`Expression<Func<User, bool>> bllExpression = x => x.Id.Id == idToFind;`

**Comment by DenisNP** [comment]
My question was about how to setup AutoMapper properly for my case.
`Expression<Func<User, bool>> bllExpression = x => x.Id.Id == idToFind;`
results in
`(FromString(x.Id).Id == 799e50f4-339f-4207-819e-194bbe206ae2)`, so `FromString` is still there.

How can I explicitly force AutoMapper to resolve methods like `FromString` and create a new expression with just built in types?

**Comment by BlaiseD** [comment]
You're getting `FromString` because it's in your configuration:
`.ForMember(u => u.Id, opt => opt.MapFrom(dbu => UserId.FromString(dbu.Id)));`

Again see issue #64.
