### ISSUE TITLE
How to convert back queryable provider after using UseAsDataSource and For

### ISSUE THREAD

**Issue by Kation** [AutoMapper/AutoMapper.Extensions.ExpressionMapping#115]
I need to use origin queryable class to call some methods.

```
IQueryable<A> source= ...;  // It is DataServiceQuery<A>
IQueryable<B> queryable = source.UseAsDataSource(mapper).For<B>();
queryable = queryable.Where(...);
```

I have a method it will convert `IQueryable` to destination class.

```
public static async Task<QueryOperationResponse<T>> QueryResponseAsync<T>(this IQueryable<T> source)
{
    if (source is DataServiceQuery<T> query)
    {
        return (QueryOperationResponse<T>)await (query.IncludeCount(true)).ExecuteAsync();
    }
    throw new NotSupportedException("This is not a odata server query.");
}
```

It will throw exception because it is `SourceSourceInjectedQuery` now.

How can I convert it to source queryable class?

**Comment by BlaiseD** [comment]
Consider creating your own helper like [this one using projection ](https://github.com/AutoMapper/AutoMapper.Extensions.OData/blob/955060847a472866dfb317748fa1bea5bcedb5c1/AutoMapper.AspNetCore.OData.EFCore/QueryableExtensions.cs#L194)-  otherwise a PR is welcome.
