### ISSUE TITLE
a FatalExecutionEngineError occur when Expression is the parameter in Orleans project

### ISSUE THREAD

**Issue by GreatToad** [AutoMapper/AutoMapper.Extensions.ExpressionMapping#131]
![图片](https://user-images.githubusercontent.com/8457261/153562595-056b4a58-430a-4c58-947b-80033ef3bcdf.png)
![图片](https://user-images.githubusercontent.com/8457261/153562619-e07e7157-11ba-4933-86ce-ebabfbb35f6d.png)

**Comment by BlaiseD** [comment]
Your description should include a simplified configuration which we can run and reproduce the exception.

**Comment by GreatToad** [comment]
> Your description should include a simplified configuration which we can run and reproduce the exception.
demo code:
https://github.com/GreatToad/OrleansDemo

use Visual Studio 2022
1 open OrleansDemo/OrleansDemo.sln,run Silo
2 open Client/Client.sln,run Client

it will occur in OrleansDemo/Grains/HelloGrain.cs on line 49
