### ISSUE TITLE
Custom type with op_equality override failed to convert

### ISSUE THREAD

**Issue by yungfu** [AutoMapper/AutoMapper.Extensions.ExpressionMapping#15]
**Source Class**
```
class Source {
    public int Value {get; set;}`
    public static bool operator == (Source x, Source y) ...
    // != and others
}

class Dest {
    public int Value {get; set;}
    //override operator "==", "!=" and related Euqals method
}

var config = new MapperConfiguratioin(cfg => {
    cfg.AddExpressionMapping();
    cfg.CreateMap<Source, Dest>();
});

var value = new Source {Value = 2};
Expression<Func<Source, bool>> expression = x=>x == value;
var mapper = config.CreateMapper();
var mapped = mapper.MapExpression<Expression<Func<Dest, bool>>>(expression);
```

Error occurred when call mapper.MapExpression with expression message: 
**System.InvalidOperationException : The operands for operator 'Equal' do not match the parameters of method 'op_Equality'.**

Seems BinaryExpression will create new expression with old **equal** methodinfo, but with new parameter type.

**Comment by BlaiseD** [comment]
You can check the [myget build](https://www.myget.org/feed/automapperdev/package/nuget/AutoMapper.Extensions.ExpressionMapping) for the update.

**Comment by yungfu** [comment]
> 
> 
> Two things:
> 
>     1. The Expression Mapper has limited support for mapping parts of the expression not related to the parameter i.e. you won't be able to map new Source() or a local variable.
> 
>     2. You are correct that the operator is not being being replaced as it should be so in 1.0.4 the following will fail where Source and Dest have operator overrides for ==:
> 
> 
> ```cs
>             Expression<Func<Source, bool>> expression = x => x == default(Source);
>             var mapped = mapper.MapExpression<Expression<Func<Dest, bool>>>(expression);
> ```

Thank you for your reply. I found it, local variable was wrapped with a new class in expression, this make the variable type cannot be found in mapping-info dictionary.

**Comment by BlaiseD** [comment]
No problem. PRs are welcome for (1). (2) has been addressed [here](https://github.com/AutoMapper/AutoMapper.Extensions.ExpressionMapping/pull/16).
