### ISSUE TITLE
Source and destination must have the same number of arguments.

### ISSUE THREAD

**Issue by kanisimoff** [AutoMapper/AutoMapper.Extensions.ExpressionMapping#17]
I use Automaper 7.0 with .Net Core 2.1 When I map 
```csharp
// Expression<Func<ReferenceDomainModel, bool>> predicate
var predicate1 = _mapper.MapExpression<Expression<Func<Reference, bool>>>(predicate);
```

When execute method where map expression, raise exception:
```json 
{
  "error": {
    "code": "ArgumentException",
    "message": "Source and destination must have the same number of arguments.",
    "target": "AutoMapper.Extensions.ExpressionMapping.MapperExtensions.DoAddTypeMappings"
  }
}
```
Classes 'Reference' and 'ReferenceDomainModel' mapped in profile as
```csharp
CreateMap<Reference, ReferenceDomainModel>();
```

In main project mapper configured:
``` csharp 
private IMapper GetAutomapperInstance()
        {
            var profiles = AppDomain.CurrentDomain.GetAssemblies()
                .SelectMany(x => x.DefinedTypes)
                .Where(type => typeof(Profile).IsAssignableFrom(type.AsType())
                               && !type.IsAbstract
                               && type.GetConstructor(Type.EmptyTypes) != null).ToList();

            // Initialize AutoMapper with each instance of the profiles found.
            var mapperConfiguration = new MapperConfiguration(a =>
            {
                a.AddExpressionMapping();
                profiles.ForEach(a.AddProfile);
            });

            return mapperConfiguration.CreateMapper();
        }
```

**Comment by BlaiseD** [comment]
It's easier to help if you provide a gist or a repo reproducing the problem.

Also a similar error was reported [here](https://github.com/AutoMapper/AutoMapper.Extensions.ExpressionMapping/issues/8) and fixed.  Your description doesn't say which version of AutoMapper.Extensions.ExpressionMapping you're using.

**Comment by kanisimoff** [comment]
Thank you for your reply. I use AutoMapper.Extensions.ExpressionMapping -Version 1.0.4. 
I will give an example of code later.

**Comment by BlaiseD** [comment]
You're correct - there is bug handling underlying type maps.  The [myget build](https://www.myget.org/feed/automapperdev/package/nuget/AutoMapper.Extensions.ExpressionMapping) should work.
