### ISSUE TITLE
System.InvalidOperationException: 'The source and destination types must be the same for expression mapping between literal types. Source Type: ObjectId, Source Description: Id, Destination Type: String, Destination Property: Id.'

### ISSUE THREAD

**Issue by kanisimoff** [AutoMapper/AutoMapper.Extensions.ExpressionMapping#18]
When I map expression I have error:
**System.InvalidOperationException: 'The source and destination types must be the same for expression mapping between literal types. Source Type: ObjectId, Source Description: Id, Destination Type: String, Destination Property: Id.'**

Repository with [error](https://github.com/kanisimoff/ForAutomapper1).
Thx.

**Comment by kanisimoff** [comment]
It work. Thank's. I will use. But why doesn’t it work if I specify mapping for individual types?
```csharp 
CreateMap<ObjectId?, string>().ConvertUsing(source => source.ToString());
CreateMap<string, ObjectId?>().ConvertUsing(source => source.ToObjectId());

CreateMap<ObjectId, string>().ConvertUsing(source => source.ToString());
CreateMap<string, ObjectId>().ConvertUsing(source => source.ToObjectId());

CreateMap<ReferenceDomainModel, ReferenceDto>();
CreateMap<ReferenceDto, ReferenceDomainModel>();
```

**Comment by BlaiseD** [comment]
The sources for mapping expressions are MapFrom, ForPath and the property maps. 

Also note that the argument for ConstructUsing is a Func not an Expression i.e it can't be modified.
