### ISSUE TITLE
Unflattening not working with UseAsDataSource or ProjectTo

### ISSUE THREAD

**Issue by Luke-1988** [AutoMapper/AutoMapper.Extensions.ExpressionMapping#24]
### Source/destination types

```
// source - EntityFramework Model types
public class Order
{
        public int ID { get; set; }

        public int customer_id { get; set; }
        public int customer_name { get; set; }
}

// destination - DTO
public class OrderDTO
{
        public int ID { get; set; }

        public customer customer { get; set; }
}

public class customer
{
        public int ID { get; set; }

        public string name { get; set; }
}
```

### Mapping configuration
```
public class MyMapperProfile : Profile
{
         public MyMapperProfile(string profileName)
                : base(profileName)
        {
            this.SourceMemberNamingConvention = new LowerUnderscoreNamingConvention();
            this.DestinationMemberNamingConvention = new LowerUnderscoreNamingConvention();

             CreateMap<OrderDTO, Order>()
                        .ForMember(m => m.id, src => src.Ignore())
                        .ReverseMap();
        }
}
```

### Versions: 
AutoMapper 8.0.0
AutoMapper.Extensions.ExpressionMapping 2.0.0

### Issue description
.UseAsDatasource and For<> or ProjectTo does not perform Unflattening as expected, whilst call of Mapper.Map<> on same Mapper configuration performs Unflattening.

### Steps to reproduce

This is working code:
```
var _entities = this.IUnitOfWork.IDataRepository.orders.ToArray();

var _dtos = entities
                                .Select(s => this.IMapper.Map<Order, OrderDTO>(s))
                                .ToArray();

// customer is properly mapped using Unflattening
Assert.AreEqual<string>(_entities.First().customer_name,    _dtos.First().customer.name);
```

This is not working code:
```
var _dtos = this.IUnitOfWork.IDataRepository.orders.
                                .UseAsDataSource(this.IMapper.ConfigurationProvider)
                                .For<OrderDTO>()
                                .ToArray();

// Here it fails, customer object at any _dto is always null.
Assert.AreEqual<string>(_entities.First().customer_name,    _dtos.First().customer.name);
```

**Comment by lbargaoanu** [comment]
ProjectTo is not for expression mapping, but it certainly do [flattening](https://gist.github.com/lbargaoanu/b271bbd6b6d6845532f77a579dc83bdf).

**Comment by Luke-1988** [comment]
Lucian, thanks. I have a problem with UseAsDataSource and Unflattening, not with ProjectTo and flattening.

**Comment by lbargaoanu** [comment]
Yes, but you mentioned ProjectTo. ProjectTo does only flattening. And your objects are reversed. In fact you entity looks like a DTO and your DTO like an entity.

**Comment by lbargaoanu** [comment]
https://stackoverflow.com/questions/53371494/automapper-8-0-missing-getpropertymaps?noredirect=1#comment93803890_53371494

**Comment by lbargaoanu** [comment]
I think @BlaiseD knows best.

**Comment by BlaiseD** [comment]
I think you should be all set if the expression mapper and the object mapper are working. Other users [here](https://github.com/AutoMapper/AutoMapper.Extensions.ExpressionMapping/issues/3) and [here](https://github.com/AutoMapper/AutoMapper.Extensions.ExpressionMapping/issues/10) seem to have been successful extracting the expressions from OData before calling AutoMapper.   Does that help?

**Comment by jbogard** [comment]
It’s not a bug i think. You’re using it in a way it’s not been designed for.

**Comment by BlaiseD** [comment]
I think @jbogard description is more accurate - not necessarily a bug because the functionality does not exist so the PersonBController sample is more like a different approach than a workaround.  Still if you have an improvement for UseAsDataSource please feel free to create a PR.

**Comment by TylerCarlson1** [comment]
To be more accurate about this issue is the UseAsDataSource isn't the problem necessarily.  It's ProjectTo that won't allow unflattering.

If instead of ToArray you did First in your example, it would of worked, because UseAsDataSource would of used Map instead of ProjectTo to tranlsate that item and the value would of come up correctly.

**Comment by jbogard** [comment]
And I don’t see ProjectTo supporting unflattening, either, without a PR.
Unflattening is still only possible in reverse maps and projecting into a
reverse map is....weird.
