### ISSUE TITLE
InvalidCastException when using UseAsDataSource in multiple layers

### ISSUE THREAD

**Issue by Gadensgaard** [AutoMapper/AutoMapper.Extensions.ExpressionMapping#26]
I am experiencing problems with UseAsDataSource in multiple layers (db > business > view). 

Unable to cast object of type 'AutoMapper.Extensions.ExpressionMapping.Impl.SourceSourceInjectedQuery`2[TBusiness]' to type 'System.Linq.IQueryable`1[TView]'.'

It works well with ProjectTo.

Gist: https://gist.github.com/Gadensgaard/4d6e56632500876736f86c79fb0e4edc

**Comment by BlaiseD** [comment]
Maybe it isn't designed for that. The following also works:
```c#
IQueryable<BusinessModel> businessDataSource1 = domainCollection.UseAsDataSource(AutoMapper.Mapper.Configuration).For<BusinessModel>().ToList().AsQueryable();
IQueryable<ViewModel> viewDataSource1 = businessDataSource1.UseAsDataSource(AutoMapper.Mapper.Configuration).For<ViewModel>();
List<ViewModel> viewDataSourceWorks = viewDataSource1.ToList(); 
```

A third option is to map expressions between layers.

**Comment by Gadensgaard** [comment]
That is not really a solution, in this example you actually evaluate the expression before translating, in that case i might as well use Mapper.Map.

What do you mean "map expressions between layers"?

**Comment by Gadensgaard** [comment]
Calling `.ToList()` will evaluate the expression, which means, for example, that I am not able to reduce the result set (`.Skip(x)`/`.Take(x)`) later on. 

I was hoping I could use this functionality to translate expressions between multiple layers (like we use `.ProjectTo<>()` currently). If it is not designed for this, then I guess the issue can be closed.

I do not have sufficient insight into ExpressionTrees to provide a PR.

**Comment by BlaiseD** [comment]
Projecting rather than calling Mapper.Map after mapping expressions could work.  Then you can still filter on the ViewModel and get a queryable back.  I haven't tried it though.
 
```c#
        public static IQueryable<TModel> DoQuery<TModel, TData>(this IQueryable<TData> query, IMapper mapper,
            Expression<Func<TModel, bool>> filter = null,
            Expression<Func<IQueryable<TModel>, IQueryable<TModel>>> queryFunc = null,
            IEnumerable<Expression<Func<TModel, object>>> includeProperties = null)
        {
            //Map the expressions
            Expression<Func<TData, bool>> f = mapper.MapExpression<Expression<Func<TData, bool>>>(filter);
            Func<IQueryable<TData>, IQueryable<TData>> mappedQueryFunc = mapper.MapExpression<Expression<Func<IQueryable<TData>, IQueryable<TData>>>>(queryFunc)?.Compile();
            ICollection<Expression<Func<TData, object>>> includes = mapper.MapIncludesList<Expression<Func<TData, object>>>(includeProperties);

            if (filter != null)
                query = query.Where(f);

            if (includes != null)
                query = includes.Aggregate(query, (q, next) => q.Include(next));

            if (mappedQueryFunc != null)
                query = mappedQueryFunc(query);

            return query.ProjectTo<TModel>(includeProperties.ToArray());
        }
```
