### ISSUE TITLE
IAsyncEnumerable support?

### ISSUE THREAD

**Issue by abbotware** [AutoMapper/AutoMapper.Extensions.ExpressionMapping#27]
I just added UseAsDataSource() to some of my code and found that all the async code fails with the following exception:

`Only sources that implement IAsyncEnumerable can be used for Entity Framework asynchronous operations.`

For now, I am changing ToListAsync().. and CountAsync() to their non-async versions, but it seems like Async support should be added.

**Comment by BlaiseD** [comment]
You can add a helper or create a PR to add a helper:

```c#
    internal static class Helpers
    {
        public static async Task<List<T>> ToListAsync<T>(this IQueryable<T> query)
        {
            return await Task.Run(() => query.ToList());
        }
    }
```

**Comment by abbotware** [comment]
That seems more like a hack/workaround... (although I havent looked at how EF Core implements IAsync) But think in order for real async support, the cancellation token needs to flow down to be able to cancel the IO ?  (In this case the database call) and ideally, cancel/break out of any loops.

All my asnyc calls honor cancellation and pass it down to the actual IO so doing your suggestion doesnt really make the call 'async'... just spawns a thread.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by BlaiseD** [comment]
You're welcome to create a PR.

**Comment by abbotware** [comment]
I may try :-)   I was thinking that UseAsDatasourceAsync(ct) would be the most appropriate approach?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by BlaiseD** [comment]
@TylerCarlson1 knows that code more than I do.  I would have thought `UseAsDataSource.For()` just returned a queryable you would then call async methods on?

I would also consider just letting EF Core handle the async calls like in the [ReadMe](https://github.com/AutoMapper/AutoMapper.Extensions.ExpressionMapping).

**Comment by abbotware** [comment]
I only started using `UseAsDataSource` when I was trying to debug another problem i had:

I attempted to use Mapper.Map on expression and pass the expression tree into EF query as en experiment.

However, when I did that I got a most unusual `InvalidOperation` exception with a message similar to `'code should never reach this'` so that made me think I am doing something fundamentally wrong / unsupported...  

Which I then came across this doc:
http://docs.automapper.org/en/stable/Expression-Translation-(UseAsDataSource).html

The entity framework example is similar to what I am trying to do:
`dataContext.OrderLines.UseAsDataSource().For<OrderLineDTO>().Where(dto => dto.Name.StartsWith("A"))`  

But it fails with the exception in my original post when I try with a `ToListAsync(ct)` appended


It does seem that there are a few topic on this subject.
http://docs.automapper.org/en/stable/Queryable-Extensions.html
https://github.com/AutoMapper/AutoMapper.Extensions.ExpressionMapping

**Comment by abbotware** [comment]
Also, in the github page for AutoMapper.Extensions.ExpressionMapping the cfg example has:

`cfg.AddExpressionMapping()`  <- is that really required?

Because its not mentioned in the 'Expression Translation' doc I looked at originally but it seemed like expression mapping was working without

**Comment by BlaiseD** [comment]
`cfg.AddExpressionMapping()` is not required if you call `IMapper.MapExpression()`.  It is required if you map expressions using `IMapper.Map()` hence the odd "**code should never reach this ...**" message.

I meant map expressions explicitly like in the ReadMe and then call EF's `ToListAsync()` on the the IQueryable.

Since this is not a bug you may get better help from StackOverflow.

Also please submit that PR when you're ready.

**Comment by abbotware** [comment]
ok - so my original code works fine if I use `MapExpression` (which is what I preferred)

while you may say it is 'not a bug' - the `Message: System.InvalidOperationException : Code supposed to be unreachable` definitely doesn't seem like a 'feature'   :-)    Seems like a good place to throw a more - 'Hey did you mean to use MapExpression instead of Map message.

**Comment by BlaiseD** [comment]
Yep - another PR for you - some AI level exception messages.  Bring your game :)

**Comment by abbotware** [comment]
Just curious - if Expression mapping via Map has to be 'enabled' - doesn't it make sense to just throw an exception if Map<Expression<..>> is called?     Otherwise what exactly are you mapping?

**Comment by BlaiseD** [comment]
You can have a class T with an expression `Exprssions<Func<T, bool>>` as a member. 

Calling Mapper.Map on T should map all the members.  Also note that `IMapper.Map` is part of AutoMapper and has no knowledge of `AutoMapper.Extensions.ExpressionMapping` at design time. 

Without `cfg.AddExpressionMapping()` it selected the best possible candidate and that candidate failed.  What you're thinking about doing is challenging - not sure how you'd go about it and I think you're in the wrong repo.

**Comment by Xriuk** [comment]
Maybe changing `SourceInjectedQueryProvider` to inherit from `IAsyncQueryProvider` instead of `IQueryProvider` would be enough? It shouldn't break other code, right?

**Comment by kmanev073** [comment]
Any updates on this? As the issue is very old, was `UseAsDatasourceAsync` ever implemented?

**Comment by Frixs** [comment]
> Any updates on this? As the issue is very old, was `UseAsDatasourceAsync` ever implemented?

I am curious about this answer as well. The issue persists for me and PR is the only workaround.
