### ISSUE TITLE
Bad LINQ when using with OData

### ISSUE THREAD

**Issue by NetTecture** [AutoMapper/AutoMapper.Extensions.ExpressionMapping#3]
I have a test case where I am using AutoMapper.ProjectTo to translate from EF (6) objects and return the IQueryable to Web Api Odata 7 (running dotnet core 2.1 on full framework).

The following simple query:

            var query1 = Repository.MandatorSet
                .Take(10)
                .ProjectTo<Api.Odata.OpsTenant>(new Dictionary<string, object>(), includes.ToArray());

works like a charm.

Replacing this with the following UseDataSource:

            var query2 = Repository.MandatorSet
                .Take(10)
                .UseAsDataSource()
                .OnError(OnException)
                .BeforeProjection(new EntityFrameworkCompatibilityVisitor())
                .For<Api.Odata.OpsTenant>(new Dictionary<string, object>(), includes.ToArray())
                .AsQueryable();
                ;

results in a ArgumentException "Argument types do not match" with no SQL generated and the stack trace:

   at System.Linq.Expressions.Expression.Bind(MemberInfo member, Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)
   at AutoMapper.Mappers.ExpressionMapper.MappingVisitor.VisitLambdaExpression[T](Expression`1 expression)
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at System.Linq.Expressions.ExpressionVisitor.Visit(ReadOnlyCollection`1 nodes)
   at AutoMapper.Mappers.ExpressionMapper.MappingVisitor.GetConvertedMethodCall(MethodCallExpression node)
   at AutoMapper.Mappers.ExpressionMapper.MappingVisitor.VisitMethodCall(MethodCallExpression node)
   at AutoMapper.Extensions.ExpressionMapping.Impl.SourceInjectedQueryProvider`2.ConvertDestinationExpressionToSourceExpression(Expression expression)
   at AutoMapper.Extensions.ExpressionMapping.Impl.SourceInjectedQueryProvider`2.Execute[TResult](Expression expression)

There is no information available on what is not working.

As can be seen, I have already added an ExpressionVisitor with the following code:

        protected override Expression VisitMethodCall(MethodCallExpression node)
        {
            // replace call to "LongCount" with "Count"            
            if (node.Method.IsGenericMethod && node.Method.DeclaringType == typeof(Queryable) && node.Method.Name == "LongCount")
            {
                var method = node.Method.DeclaringType.GetMethods(BindingFlags.Public | BindingFlags.Static).First(m => m.Name == "Count");
                method = method.MakeGenericMethod(node.Method.GetGenericArguments());
                return Expression.Call(method, node.Arguments);
            }

            return base.VisitMethodCall(node);
        }

but I seem to be unable to get the Lambda that the 2nd query is generating. Query 1 - the one using ProjectTO, generates:

.Call System.Linq.Queryable.Select(
    .Call System.Linq.Queryable.Take(
        .Call .Constant<System.Data.Entity.Core.Objects.ObjectQuery`1[DAL.MyTypes.G.TMandator]>(System.Data.Entity.Core.Objects.ObjectQuery`1[DAL.MyTypes.G.TMandator]).MergeAs(.Constant<System.Data.Entity.Core.Objects.MergeOption>(AppendOnly))
        ,
        10),
    '(.Lambda #Lambda1<System.Func`2[DAL.MyTypes.G.TMandator,Api.Odata.OpsTenant]>))

.Lambda #Lambda1<System.Func`2[DAL.MyTypes.G.TMandator,Api.Odata.OpsTenant]>(DAL.MyTypes.G.TMandator $dtoTMandator) {
    .New Api.Odata.OpsTenant(){
        Buildings = .Call System.Linq.Enumerable.ToList(.Call System.Linq.Enumerable.Select(
                $dtoTMandator.Buildings,
                .Lambda #Lambda2<System.Func`2[DAL.MyTypes.Ob.TBuilding,Api.Odata.CoreBuilding]>)),
        Identity = $dtoTMandator.Identity,
        Name = $dtoTMandator.Name
    }
}

.Lambda #Lambda2<System.Func`2[DAL.MyTypes.Ob.TBuilding,Api.Odata.CoreBuilding]>(DAL.MyTypes.Ob.TBuilding $dtoTBuilding) {
    .New Api.Odata.CoreBuilding(){
        Identity = $dtoTBuilding.Identity,
        Name = $dtoTBuilding.LongName
    }
}

whcih is as simple as it ets (as can be seen). For Query 2 - the UseDataSource, all I can ever seem to get is

.Constant<System.Linq.EnumerableQuery`1[Api.Odata.OpsTenant]>(Api.Odata.OpsTenant[])

I will gladly show the generated underlying Lambda if I can get my hands on it.

Whatever it is, the generated queryable and usability is not identical with the projection in the base automapper.

Executing Query2 prior to returning it ( var re = query2.ToArray(); ) works and generates the result.

I can likely provide a multi project repro case, I am willing to run any analysis that helps on my test project, but I am unsure at the moment how to even get the lambda that actually is having problems here -I assume it has something to do with what OData does, but without seeing what it is.... On Exception sadly does not provide any more context information.

**Comment by BlaiseD** [comment]
@jbogard @TylerCarlson1 - your area ? :)

**Comment by TylerCarlson1** [comment]
This ones pretty involved.  My guess is `.AsQueryable()` is calling the UseAsDataSource to enumerate itself and is returning an array, which then is the input for EnumerableQuery which is the array.
That's why you see 
```
.Constant<System.Linq.EnumerableQuery`1[Api.Odata.OpsTenant]>(Api.Odata.OpsTenant[])
```

UseAsDataSource returns a queryable so there's no reason to say AsQueryable on top of it.  Especially when returning it through OData.  I don't know if OData 7 has changed anything for this, but it looks like AsQueryable is the culprit as far as I can tell.

http://docs.automapper.org/en/stable/Understanding-your-mapping.html can help make the lambdas more readable.

**Comment by NetTecture** [comment]
I tried removing the AsQueryable and now i get a call into OnException.

            var query2 = Repository.MandatorSet
                .Take(10)
                .UseAsDataSource()
                .OnError(OnException)
                .BeforeProjection(new EntityFrameworkCompatibilityVisitor())
                .For<Api.Odata.OpsTenant>(new Dictionary<string, object>(), includes.ToArray())
                ;

is now a 

{AutoMapper.Extensions.ExpressionMapping.Impl.SourceSourceInjectedQuery<DAL.MyTypes.G.TMandator, Api.Odata.OpsTenant>} 

which sounds correct (and yes, the class terms on my end are not really logical - trying to rework some old debt).

Problem is that whileI can do

                var re = query2.ToArray();

returning the query2 to Odata results in OnError...

$exception | {"The method or operation is not implemented."} | System.NotImplementedException

THere is no additional information available - no inner exception, no method name. I would assume some method is not implemented that OData7 now requiers.

**Comment by BlaiseD** [comment]
@NetTecture - I advise a small reproducible sample via gist or otherwise.  It's easier to help with a failing sample.

**Comment by NetTecture** [comment]
Gist you can forget - but i have a pretty minimal example in 3 projects. Because the error happens before sql generation, I can upload stripped zip - no db necessary. Please provde me a safe place to upload a zip

**Comment by BlaiseD** [comment]
Maybe create a repo [here](https://github.com/NetTecture?tab=repositories) ?

**Comment by NetTecture** [comment]
@BlaiseD Did you have a look at the example? Just realized I did not mention you to see it.

Here is the link: https://github.com/NetTecture/Am-Datasource-Issue

**Comment by BlaiseD** [comment]
I did download - couldn't build though.

- First make it as simple as possible for anyone trying to help - it should unzip and build.
- Second - you may want to download this repo (AutoMapper.Extensions.ExpressionMapping) and AutoMapper. You know the rest - reference this repo from your project.  You may also want to reference the AutoMapper project (instead of the nuget package) from ExpressionMapping - debug your project to point you to exactly what's blowing up.

**Comment by NetTecture** [comment]
If it does not build - what are you using? Because it is as simple as it gets.

* Requires .net framework 4.7.2 current dotnet standard environments.

If it doesn ot build, wahat error do you get?

Otherwise it is all there..

The problem is that I am not sure that your CODE is blowing - more that you build a wrong expression tree. Totally not "easy to debug" by definition.

**Comment by NetTecture** [comment]
@BlaiseD @jbogard Ok, I have now reduced the repro case toe the absolute minimum that makes sense. ONE project (which sadly still requires a current visualstudio and .NET 472 support). There are a number of source files, among them:
* 2 for the model(s)
* 2 for the database side model
* 1 for the dbcontext
* 1 for the controller
* 2 just required / implemented by asp.net core 2.1 standard template (program.cs, startup.cs).

If you still can not compile it, maybe you should say the error here.

There is no way to make this easier - odata is vs database and everything is as much simplifie d as possible. This is a dotnet core asp.net proejct reconfigured to use the full .net 472 - a supported scenario - so I can use full Entity Framework.

**Comment by NetTecture** [comment]
@BlaiseD And because you wanted it all in one in your repository I forked and added the whole repro case

https://github.com/NetTecture/AutoMapper.Extensions.ExpressionMapping/tree/bug/odata7

Fork and compile. Does not get easier.

I followed your request to say - ah...

> debug your project to point you to exactly what's blowing up.

OK, here is the news.

For the query:

            var query2 = Repository.MandatorSet
                .Take(10)
                .UseAsDataSource()
                .OnError(OnException)
                .BeforeProjection(new EntityFrameworkCompatibilityVisitor())
                .For<Model.OpsTenant>(new Dictionary<string, object>(), includes.ToArray())
                ;
I now get the following stack trace:

   at Api.Odata.Web.Controllers.OpsTenantController.OnException(Exception obj) in C:\Work\AutoMapper.Extensions.ExpressionMapping\src\Api.Odata.Web\Controllers\OpsTenantController.cs:line 143
   at AutoMapper.Extensions.ExpressionMapping.Impl.SourceSourceInjectedQuery`2.GetEnumerator() in C:\Work\AutoMapper.Extensions.ExpressionMapping\src\AutoMapper.Extensions.ExpressionMapping\Impl\SourceInjectedQuery.cs:line 69
   at AutoMapper.Extensions.ExpressionMapping.Impl.SourceSourceInjectedQuery`2.System.Collections.IEnumerable.GetEnumerator() in C:\Work\AutoMapper.Extensions.ExpressionMapping\src\AutoMapper.Extensions.ExpressionMapping\Impl\SourceInjectedQuery.cs:line 74
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteResourceSet(IEnumerable enumerable, IEdmTypeReference resourceSetType, ODataWriter writer, ODataSerializerContext writeContext)
   at Microsoft.AspNet.OData.Formatter.ODataOutputFormatterHelper.WriteToStream(Type type, Object value, IEdmModel model, ODataVersion version, Uri baseAddress, MediaTypeHeaderValue contentType, IWebApiUrlHelper internaUrlHelper, IWebApiRequestMessage internalRequest, IWebApiHeaders internalRequestHeaders, Func`2 getODataMessageWrapper, Func`2 getEdmTypeSerializer, Func`2 getODataPayloadSerializer, Func`1 getODataSerializerContext)
   at Microsoft.AspNet.OData.Formatter.ODataOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)

No sensible other information easily visible.

**Comment by NetTecture** [comment]
Oh, as a side note: For Odata 7 you will need the nightly builds for nuget which you can get at https://www.myget.org/F/webapinetcore/ - not sure nuget accepts any sort of config file which I can embedd into the solution. Yeah, my fault on that. Sorry.

**Comment by BlaiseD** [comment]
Actually you can also get a queryable back by projecting - still filtering, sorting, expanding against the OData model - so you're all set.  With regard to UseAsDataSource PRs are welcome.

```csharp
        [HttpGet]
        [EnableQuery()]
        public IQueryable<OpsTenant> Get(ODataQueryOptions<Api.Odata.OpsTenant> options)
        {
            IQueryable<OpsTenant> query = Repository.MandatorSet.GetQuery<OpsTenant, TMandator>(options);
            return query;
        }

        public static IQueryable<TModel> GetQuery<TModel, TData>(this IQueryable<TData> query, ODataQueryOptions<TModel> options)
            where TModel : class
        {
            var includes = GetIncludesFromExpandClause(options.SelectExpand);
            Expression<Func<TModel, object>>[] includeExpressions = includes.BuildIncludes<TModel>().ToArray();
            Expression<Func<TModel, bool>> filter = options.Filter.ToFilterExpression<TModel>();
            Expression<Func<IQueryable<TModel>, IQueryable<TModel>>> queryableExpression = options.GetQueryableExpression();

            return query.GetQueryEF6<TModel, TData>(Mapper.Instance, filter, queryableExpression, includeExpressions);
        }

        public static IQueryable<TModel> GetQueryEF6<TModel, TData>(this IQueryable<TData> query, IMapper mapper,
            Expression<Func<TModel, bool>> filter = null,
            Expression<Func<IQueryable<TModel>, IQueryable<TModel>>> queryFunc = null,
            IEnumerable<Expression<Func<TModel, object>>> includeProperties = null)
        {
            //Map the expressions
            Expression<Func<TData, bool>> f = mapper.MapExpression<Expression<Func<TData, bool>>>(filter);
            Func<IQueryable<TData>, IQueryable<TData>> mappedQueryFunc = mapper.MapExpression<Expression<Func<IQueryable<TData>, IQueryable<TData>>>>(queryFunc)?.Compile();
            ICollection<Expression<Func<TData, object>>> includes = mapper.MapIncludesList<Expression<Func<TData, object>>>(includeProperties);

            if (filter != null)
                query = query.Where(f);

            if (includes != null)
                query = includes.Aggregate(query, (q, next) => q.Include(next));

            if (mappedQueryFunc != null)
                query = mappedQueryFunc(query);

            return query.ProjectTo<TModel>(includeProperties.ToArray());
        }
```
