### ISSUE TITLE
"Method not found" exception upgrading to AutoMapper v8.1.0.

### ISSUE THREAD

**Issue by gamblen** [AutoMapper/AutoMapper.Extensions.ExpressionMapping#30]
I have upgraded to AutoMapper v8.1.0 and now see this exception:

Method not found: 'System.Linq.Expressions.LambdaExpression[] AutoMapper.QueryableExtensions.IExpressionBuilder.GetMapExpression(System.Type, System.Type, System.Collections.Generic.IDictionary`2<System.String,System.Object>, System.Reflection.MemberInfo[])'.

Reverting to AutoMapper v8.0.0 works.

The method looks unaltered in the code, and I think the exception is incorrect, but when trying to build the current master branch against AutoMapper v8.1.0, it fails as some static methods have been removed.

**Comment by BlaiseD** [comment]
It's easier to help if you provide a gist or other sample code reproducing the error.

**Comment by gamblen** [comment]
https://gist.github.com/gamblen/9b52d15e59941a412ac43c488f8477fc

Here is a sample that shows.  If you change the version of AutoMapper to version 8.0.0 it works, but as 8.1.0 it fails.

**Comment by BlaiseD** [comment]
Yep - there are breaking changes.  Looking at the damage ...

**Comment by BlaiseD** [comment]
Should be fixed now in PR #31 [v2.0.2](https://www.nuget.org/packages/AutoMapper.Extensions.ExpressionMapping/).
