### ISSUE TITLE
Type Binary and Conversion expressions are not being mapped as expected.

### ISSUE THREAD

**Issue by scmccart** [AutoMapper/AutoMapper.Extensions.ExpressionMapping#33]
Hey, I'm trying to map an expression that does a type check and a cast involving derived types, but the types in the check and cast expressions are not being mapped. I've cloned the repo and created a new test based on ExpressionMappingPropertyFromBaseClass, altering the Because_of to below.

```csharp
protected override void Because_of()
{
    //Arrange
    _source = new List<BaseEntity> {
        new Entity { Id = Guid.NewGuid(), Name = "Sofia" },
        new Entity { Id = Guid.NewGuid(), Name = "Rafael" },
        new BaseEntity { Id = Guid.NewGuid() }
    };

    // Act
    Expression<Func<BaseDTO, bool>> dtoQueryExpression = r => (r is DTO ? ((DTO)r).Name : "") == "Sofia";
    var entityQueryExpression = Mapper.Map<Expression<Func<BaseEntity, bool>>>(dtoQueryExpression);
    entityQuery = _source.AsQueryable().Where(entityQueryExpression);
}
```

I would expect the expression to map to the equivalent of this,
```csharp
Expression<Func<BaseEntity, bool>> mapped = r => (r is Entity ? ((Entity)r).Name : "") == "Sofia";
```

However, the output is currently the equivalent of,
```csharp
Expression<Func<BaseEntity, bool>> mapped = r => (r is DTO ? ((DTO)r).Name : "") == "Sofia";
```

I'll attempt a fix and PR but any thoughts or guidance would be appreciated. The full failing test can be seen in [my fork](https://github.com/scmccart/AutoMapper.Extensions.ExpressionMapping/blob/issue-derived-type-expressions/tests/AutoMapper.Extensions.ExpressionMapping.UnitTests/ExpressionMappingPropertyFromDerviedType.cs).

**Comment by BlaiseD** [comment]
I would look at the [expression visitor](https://github.com/AutoMapper/AutoMapper.Extensions.ExpressionMapping/blob/6d46125894b0235db6c36490357d65232fffe94b/src/AutoMapper.Extensions.ExpressionMapping/XpressionMapperVisitor.cs#L16)  and figure out where it may be possible to replace the nodes.  You may need to override a method not yet [implemented](https://docs.microsoft.com/en-us/dotnet/api/system.linq.expressions.expressionvisitor?view=netframework-4.8) in XpressionMapperVisitor.

**Comment by leowns** [comment]
I have the same issue in my project. Is there any update on this?

**Comment by BlaiseD** [comment]
@leowns  - I think the question was what was the best way to configure the derived and base types to map - then provide a user friendly error message if the configuration was incorrect.

@scmccart's design was a good option.  Feel free to submit a PR.

**Comment by BlaiseD** [comment]
The error message was `No coercion operator is defined between types 'BaseEntity' and 'DTO'.` if the derived type mapping had been left out.  I suppose it wasn't that bad.

**Comment by BlaiseD** [comment]
Heads up @leowns [see release 3.1.0-preview02](https://www.nuget.org/packages/AutoMapper.Extensions.ExpressionMapping/3.1.0-preview02).

You'll have to configure the subtype/supertype using `IMappingExpression.Include()`/`IMappingExpression.IncludeBase()`.
