### ISSUE TITLE
Create profile like Classic AutoMapper

### ISSUE THREAD

**Issue by rmszc81** [AutoMapper/AutoMapper.Extensions.ExpressionMapping#39]
Hello @jbogard and @ALL,

I have two questions:

1) How to create profiles (like classic AutoMapper profiles) for Expression Mapping? Can you provide an example?

2) In classic AutoMapper, we can use .Map(object, sourceType, targetType). Is it possible to use this for ExpressionMapping too?

Thanks!

**Comment by BlaiseD** [comment]
1. Profiles are the same as with AutoMapper.
2. You mean .Map(object, tyorof(Expression<TSource>), tyorof(Expression<TTarget>).  I'm sure it does.

This question is better suited for StackOverflow. 

If you have discovered a bug please provide a reproducible sample we can run and see fail.

**Comment by BlaiseD** [comment]
Also from you original title remember to activate ExpressionMapping.

```c#
var mapper = new Mapper(new MapperConfiguration(cfg => {
    cfg.AddExpressionMapping();
	// Rest of your configuration
}));
```
