### ISSUE TITLE
NotSuportedException when mapping entities with complex types using Entity Framework

### ISSUE THREAD

**Issue by Gadensgaard** [AutoMapper/AutoMapper.Extensions.ExpressionMapping#5]
I am implementing an OData service, and use AutoMapper with ExpressionMapping to map the OData entities to our domain model (EF Code First). 

When projecting OData entities containing complex types, i get a System.NotSupportedException.

I have configured the properties with complex types with the AllowNull option, and it is working fine when using ProjectTo, but not when using UseAsDataSource.For. I am preferring UseAsDataSource.For to allow usage of OnEnumerated callback. 

The issue is previously described here, but for ProjectTo:
https://github.com/AutoMapper/AutoMapper/issues/925

**Comment by BlaiseD** [comment]
It's easier to help with a failing sample.  Please include the code here, create a gist or add a repo [here](https://github.com/Gadensgaard)  producing the exception.
