### ISSUE TITLE
UseAsDataSource failing with interfaces on the DTO.

### ISSUE THREAD

**Issue by NetTecture** [AutoMapper/AutoMapper.Extensions.ExpressionMapping#55]
Not a complete example, but the following code:

                        var tname = typeof(T).Name;
                        var pName = typeof(P).Name;

                        var query = Repository.Set<T>()
                            // No tracking. 
                            //.AsNoTracking()
                            .UseAsDataSource(MapperConfiguration)
                            .For<P>(EmptyParams, includes)
                            //.ProjectTo<P>(MapperConfiguration, EmptyParams, includes)
                        ;

where the following names are resolved at runtime (to show those are real object names as per naming convention):

  | Name | Value | Type
-- | -- | -- | --
  | tname | "GTMandator" | string

  | Name | Value | Type
-- | -- | -- | --
  | pName | "Account" | string

results upon execution on a runtime error the moment the following where clause is added to query:

.Where(x => x.Identity == key);

I get an exception like this:

System.ArgumentException
  HResult=0x80070057
  Message=Property 'System.Guid GIdentity' is not defined for type 'Api.Odata.IIdentityEntity' (Parameter 'property')
  Source=System.Linq.Expressions

  StackTrace:
   at System.Linq.Expressions.Expression.Property(Expression expression, PropertyInfo property)
   at AutoMapper.Internal.ExpressionFactory.ReplaceParameters(LambdaExpression exp, Expression[] replace)
   at AutoMapper.ExpressionExtensions.ReplaceParameters(LambdaExpression exp, Expression[] replace)
   at AutoMapper.Mappers.ExpressionMapper.MappingVisitor.VisitMember(MemberExpression node)
   at AutoMapper.Mappers.ExpressionMapper.MappingVisitor.VisitBinary(BinaryExpression node)
   at AutoMapper.Mappers.ExpressionMapper.MappingVisitor.VisitLambdaExpression[T](Expression`1 expression)
   at AutoMapper.Mappers.ExpressionMapper.MappingVisitor.VisitLambda[T](Expression`1 node)
   at AutoMapper.Mappers.ExpressionMapper.MappingVisitor.<>c__23`1.<VisitAllParametersExpression>b__23_9(Expression e, ExpressionVisitor v)
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at AutoMapper.Mappers.ExpressionMapper.MappingVisitor.VisitAllParametersExpression[T](Expression`1 expression)
   at AutoMapper.Mappers.ExpressionMapper.MappingVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at System.Linq.Expressions.ExpressionVisitor.Visit(ReadOnlyCollection`1 nodes)
   at AutoMapper.Mappers.ExpressionMapper.MappingVisitor.GetConvertedMethodCall(MethodCallExpression node)
   at AutoMapper.Mappers.ExpressionMapper.MappingVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.ExpressionVisitor.Visit(ReadOnlyCollection`1 nodes)
   at AutoMapper.Mappers.ExpressionMapper.MappingVisitor.GetConvertedMethodCall(MethodCallExpression node)
   at AutoMapper.Mappers.ExpressionMapper.MappingVisitor.VisitMethodCall(MethodCallExpression node)
   at AutoMapper.Extensions.ExpressionMapping.Impl.SourceInjectedQueryProvider`2.ConvertDestinationExpressionToSourceExpression(Expression expression)
   at AutoMapper.Extensions.ExpressionMapping.Impl.SourceInjectedQueryProvider`2.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
   at Api.Odata.Web.Code.ODataIdentityEntityController`2.Get(Guid key, ODataQueryOptions`1 options) in C:\Work\OBB\Source.Backend\Api.Odata.Web\Code\ODataIdentityEntityController.cs:line 43

  This exception was originally thrown at this call stack:
	System.Linq.Expressions.Expression.Property(System.Linq.Expressions.Expression, System.Reflection.PropertyInfo)
	AutoMapper.Internal.ExpressionFactory.ReplaceParameters(System.Linq.Expressions.LambdaExpression, System.Linq.Expressions.Expression[])
	AutoMapper.ExpressionExtensions.ReplaceParameters(System.Linq.Expressions.LambdaExpression, System.Linq.Expressions.Expression[])
	AutoMapper.Mappers.ExpressionMapper.MappingVisitor.VisitMember(System.Linq.Expressions.MemberExpression)
	AutoMapper.Mappers.ExpressionMapper.MappingVisitor.VisitBinary(System.Linq.Expressions.BinaryExpression)
	AutoMapper.Mappers.ExpressionMapper.MappingVisitor.VisitLambdaExpression<T>(System.Linq.Expressions.Expression<T>)
	AutoMapper.Mappers.ExpressionMapper.MappingVisitor.VisitLambda<T>(System.Linq.Expressions.Expression<T>)
	AutoMapper.Mappers.ExpressionMapper.MappingVisitor.VisitAllParametersExpression.AnonymousMethod__23_9(System.Linq.Expressions.Expression, System.Linq.Expressions.ExpressionVisitor)
	System.Linq.Enumerable.Aggregate<TSource, TAccumulate>(System.Collections.Generic.IEnumerable<TSource>, TAccumulate, System.Func<TAccumulate, TSource, TAccumulate>)
	AutoMapper.Mappers.ExpressionMapper.MappingVisitor.VisitAllParametersExpression<T>(System.Linq.Expressions.Expression<T>)
    ...
    [Call Stack Truncated]

The only way this enters is as following:

* Account implements IIDentityEntity, which looks like this:

    public interface IIdentityEntity
    {

        Guid Identity { get; }

    }

I use it as a base interface so I can use one generic controller which will automatically know what the key on the entity is. It defines the Identity as Identity which then is mapped into GIdentity on the EFCore data source side.

Somewhere in there the mapping visitor is getting confused and is not managing to map that interface to the backend property which it SOMEHOW assumes to be on the interface.

**Comment by BlaiseD** [comment]
Easier to help with a complete failing sample.

**Comment by NetTecture** [comment]
Working on making a repro case.

**Comment by NetTecture** [comment]
@BlaiseD Done ;) It is related to inheritance and parameters.

You find a ful ltest case at https://github.com/NetTecture/Automapper.Bugs.ParentMapping - yes, the name is off. I reuse an old repro.

* Grab the source code from that repository using current visual studio. 3.1.1 dotnet sdk.
* There is one test for running in test exploder: Test.ProjectTo DataSourceINterface

To properly debug:
* But a breakpoint in MappingSourceForEvent, line 22
* If it his the breakpooint, the expresion (variable xp) reads:

.Call System.Linq.Queryable.Where(
    .Constant<System.Linq.EnumerableQuery`1[Tests.ProjectTo.ApiModel.Event]>(Tests.ProjectTo.ApiModel.Event[]),
    '(.Lambda #Lambda1<System.Func`2[Tests.ProjectTo.ApiModel.Event,System.Boolean]>))

.Lambda #Lambda1<System.Func`2[Tests.ProjectTo.ApiModel.Event,System.Boolean]>(Tests.ProjectTo.ApiModel.Event $x) {
    ((Tests.ProjectTo.ApiModel.IIntegerEntity)$x).Id == .Constant<Tests.ProjectTo.MappingSourceIntKey`2+<>c__DisplayClass0_0[Tests.ProjectTo.DataModel.TEvent,Tests.ProjectTo.ApiModel.Event]>(Tests.ProjectTo.MappingSourceIntKey`2+<>c__DisplayClass0_0[Tests.ProjectTo.DataModel.TEvent,Tests.ProjectTo.ApiModel.Event]).key
}

The next line will blow:

System.ArgumentException: 'Property 'Int32 Id' is not defined for type 'Tests.ProjectTo.ApiModel.IIntegerEntity' (Parameter 'property')'

But it IS defined - in fact it is the ONE property that is defined there, as IIntegerEntity reads:

    public interface IIntegerEntity
    {
        Int32 Id { get; set; }
    }

This matches 100% my use case - basically in odata web api. As my controllers fall into 3 categories for the key, I use interfaces and a sub element to ultimately have all logi in one basic abstract one. This blows with useasdatasource. IT seems it goes wrong somewhere in the inheritance hierarchy..

In thepast I was using ProjectTo which worked in ef, but stops working in efcore.

**Comment by BlaiseD** [comment]
Two problems here:
1. UseAsDataSource is can't map is throwing an exception trying to map the expression.  You'd have to create a PR to make it work.
2. EF Core will also throw the following exception if it's translated.

```
System.InvalidOperationException
  HResult=0x80131509
  Message=The LINQ expression 'DbSet<TEvent>
    .Where(t => ((IIntegerEntity)t).Id == __key_0)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
  Source=Microsoft.EntityFrameworkCore
```

Instead I'd recommend mapping the expression directly
```c#
        public IQueryable<D> GetQuery(IMapper mapper,
            Expression<Func<D, bool>> filter)
        {
            var repository = new Repository();
            IQueryable<E> query = repository.Set<E>().AsNoTracking();
            Expression <Func<E, bool>> f = mapper.MapExpression<Expression<Func<E, bool>>>(filter);

            if (filter != null)
                query = query.Where(f);
            return mapper.ProjectTo<D>(query);
        }
```

Instead of GetByKey just pass in an expression - more flexible anyway:
```c#
    public class MappingSourceIntKey<E,D> : MappingSource<E,D>
        where E : class
        where D : IIntegerEntity
    {
        public IQueryable<D> Get(Expression<Func<D, bool>> filter)
        {
            var query = GetQuery(AutoMapperConfiguration.Mapper, filter);
            return query;
        }
    }
```

In GetEvent do this:
```c#
    public class MappingSourceForEvent : MappingSourceIntKey<TEvent, ApiModel.Event>
    {
        public Event GetEvent(int key)
        {
            var query = Get(x => x.Id == key);
            var item = query.FirstOrDefault();
            return item;
        }
    }
```

Of course you'll need your mapper:

```c#
    public static class AutoMapperConfiguration
    {
        static AutoMapperConfiguration()
        {
//
            Mapper = Instance.CreateMapper();
        }
        public static IMapper Mapper { get; }
    }
```

**Comment by NetTecture** [comment]
@BlaiseD Problems with that:

* It still is a bug. The moment I take out one of the inheritance hierarchy - it works. This is NOT a problem with EfCore at all - it is purely a problem with UseAsDataSource. The same mapping works perfectly if I directly apply it. For me, though, this would mean having a ridiculous amount of redundant code. GetByKey equivalents are exposed for about 30+ endpoints. Because they al fall into 3 different categories (depending on key type) I introduced a common controller level (yes, the real code is webapi) to handle those common cases in one central place. As you so nocely say:

1.	UseAsDataSource is can't map is throwing an exception trying to map the expression. You'd have to create a PR to make it work.

No. I am not a specialist in this code and it is complex. I proivded a bug report and repro case. I do not even know how to make a PR for this because for this I first would have to actually udnerstand the code. It still is a bug, is it not?

* GetByKey is mandated like this pretty much. There is no way to rewrite the Odata handling in the odata library. You do not pass in an expression, you do return an IQueryable an the expression is then applied to it by the framework. The problem is that there is GetByKey - yes, perfect, I passi n the exception - and List. And LIST - returns IQueryable to the controller so it adds conditions based on it's own interpretation of the query string.

Techcnially it means UseAsDataSource is absolutely unusable on 2 levels now - it is buggy not handling something as simple as this interface scenario, and second it is unusable in dnc because of yet another limitation of EfCore. Time to rip ou this crap (efcore) - then I can also throw out UseAsDataSource because interesting enough in .net using EntityFramework ProjectTo worked perfectly (as in: it acutaloly WORKED).

Still, I reported this as a bug which fails to map the expression, and that is what it is. I also open a bug report for the EfCore team - for them to look at maybe in 2030 or so when they get around understanding that LINQ is not something that has only simple use cases.

**Comment by NetTecture** [comment]
@BlaiseD There is also another problem. You nicely point out that once the first issue is fixed, another one remains:

System.InvalidOperationException
  HResult=0x80131509
  Message=The LINQ expression 'DbSet<TEvent>
    .Where(t => ((IIntegerEntity)t).Id == __key_0)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
  Source=Microsoft.EntityFrameworkCore

From an EfCore point of view - yes, once you throw carap at it is till bug out. It is way less forgiving. See, the problem in the above is that it simply means that expression translation does not happen properly becuase there is no reason for the cast to be there.

`.Where(t` => ((IIntegerEntity)t).Id == __key_0)' could not be translated.

may not translate, but

`.Where(t` => Id == __key_0)' could not be translated.

does and that case makes no sense as from the inheritance hierarchy it is defined that ANY object there already has Id. This does run down to the inheritance generics somehow pulluting the tree, which should imho not happen. I can rewrite this in a more simple form (loosing inheritance) and then the generated condition does NOT have the cast in the where and works perfectly.

So, bug report on the expression translator which obviously does not translate this expression properly and introduces a cast.

**Comment by BlaiseD** [comment]
Note:

- UseAsDataSource is opaque.
- The expression mapper here `Expression<Func<E, bool>> f = mapper.MapExpression<Expression<Func<E, bool>>>(filter);` is not the same as the translator used by UseAsDataSource.

With your own helpers like (following) you can isolate the problem to **expression mapping**, **object mapping** or **projecting the queryable**. So first determine whether you need UseAsDataSource at all.

```c#
    public static class Helpers
    {
        public static TReturn QueryAsync<TModel, TData, TModelReturn, TDataReturn, TReturn>(this IQueryable<TData> query, IMapper mapper,
            Expression<Func<IQueryable<TModel>, TModelReturn>> queryFunc = null,
            ICollection<Expression<Func<IQueryable<TModel>, IIncludableQueryable<TModel, object>>>> includeProperties = null)
        {
            Func<IQueryable<TData>, TDataReturn> mappedQueryFunc = mapper.MapExpression<Expression<Func<IQueryable<TData>, TDataReturn>>>(queryFunc).Compile();
            ICollection<Expression<Func<IQueryable<TData>, IIncludableQueryable<TData, object>>>> includes = mapper.MapIncludesList<Expression<Func<IQueryable<TData>, IIncludableQueryable<TData, object>>>>(includeProperties);

            if (includes != null)
                query = includes.Select(i => i.Compile()).Aggregate(query, (q, next) => q = next(q));

            TDataReturn result = mappedQueryFunc(query);

            return typeof(TReturn) == typeof(TDataReturn) ? (TReturn)(object)result : mapper.Map<TDataReturn, TReturn>(result);
        }

        public static IQueryable<TModel> GetQuery<TModel, TData>(this IQueryable<TData> query, IMapper mapper,
            Expression<Func<TModel, bool>> filter = null,
            Expression<Func<IQueryable<TModel>, IQueryable<TModel>>> queryFunc = null,
            ICollection<Expression<Func<IQueryable<TModel>, IIncludableQueryable<TModel, object>>>> includeProperties = null)
        {
            Expression<Func<TData, bool>> f = mapper.MapExpression<Expression<Func<TData, bool>>>(filter);
            Func<IQueryable<TData>, IQueryable<TData>> mappedQueryFunc = mapper.MapExpression<Expression<Func<IQueryable<TData>, IQueryable<TData>>>>(queryFunc)?.Compile();
            ICollection<Expression<Func<IQueryable<TData>, IIncludableQueryable<TData, object>>>> includes = mapper.MapIncludesList<Expression<Func<IQueryable<TData>, IIncludableQueryable<TData, object>>>>(includeProperties);

            if (filter != null)
                query = query.Where(f);

            if (includes != null)
                query = includes.Select(i => i.Compile()).Aggregate(query, (q, next) => q = next(q));

            return mappedQueryFunc != null
                    ? mapper.ProjectTo<TModel>(mappedQueryFunc(query))
                    : mapper.ProjectTo<TModel>(query);
        }

        public static ICollection<TModel> Get<TModel, TData>(this IQueryable<TData> query, IMapper mapper,
            Expression<Func<TModel, bool>> filter = null,
            Expression<Func<IQueryable<TModel>, IQueryable<TModel>>> queryFunc = null,
            ICollection<Expression<Func<IQueryable<TModel>, IIncludableQueryable<TModel, object>>>> includeProperties = null)
        {
            Expression<Func<TData, bool>> f = mapper.MapExpression<Expression<Func<TData, bool>>>(filter);
            Func<IQueryable<TData>, IQueryable<TData>> mappedQueryFunc = mapper.MapExpression<Expression<Func<IQueryable<TData>, IQueryable<TData>>>>(queryFunc)?.Compile();
            ICollection<Expression<Func<IQueryable<TData>, IIncludableQueryable<TData, object>>>> includes = mapper.MapIncludesList<Expression<Func<IQueryable<TData>, IIncludableQueryable<TData, object>>>>(includeProperties);

            if (filter != null)
                query = query.Where(f);

            if (includes != null)
                query = includes.Select(i => i.Compile()).Aggregate(query, (q, next) => q = next(q));

            ICollection<TData> result = mappedQueryFunc != null ? mappedQueryFunc(query).ToList() : query.ToList();

            return mapper.Map<IEnumerable<TData>, IEnumerable<TModel>>(result).ToList();
        }
    }
```


Next if you agree you don't need UseAsDataSource, recreate the problem using your helpers.  Also include code to create the database.  The example I provided (previous post) translated the expression.

So recreate the problem without UseAsDataSource and we can proceed from that point.

**Comment by NetTecture** [comment]
@BlaiseD Nice to see this closed.

Anyhow, I have some news for you. I managed to work around it - and the workaround indicates to an internal bug which LIKELY goes back to a changed behavior.

Anyhow, here is my new repro.

* Download the same repository as before:

https://github.com/NetTecture/Automapper.Bugs.ParentMapping

The tests are now in a file TestsMappingSource, both green because both except different exceptions.

* TestCallBroken throws the ArgumentException as before. It goes to MappingSourceBrokenForEvent, then MappingSouceBrokenIntKey.
* TestsCallFixed throws TargetInvocationException containing the SqlException opening the db connection. It uses MappingSourceFixedForEvent which goes to MappingSourceFixedIntKey.

The difference is....

MappingSourceBrokenIntKey:

    public class MappingSourceBrokenIntKey<E,D> : MappingSource<E,D>
        where E : class
        where D : IIntegerEntity
    {

MappingSoruceFixedIntKey:

    public class MappingSourceFixedIntKey<E,D> : MappingSource<E,D>
        where E : class
        where D : class,  IIntegerEntity
    {

See the last line defining D? In the failing one it is not defined to be a reference type. I can only assume this leads to the error.

**Comment by BlaiseD** [comment]
That's interesting.    If you inspect the [debug view](https://docs.automapper.org/en/stable/Understanding-your-mapping.html) it's doing the following:

Fixed case:
```c#
(Tests.ProjectTo.ApiModel.Event $x) =>   $x.Id == constant;
```
Broken case:
```c#
(Tests.ProjectTo.ApiModel.Event $x) =>   ((Tests.ProjectTo.ApiModel.IIntegerEntity)$x).Id == constant;
```

So in the fixed case `where D: IIntegerEntity` helps the compiler but the expression doesn't use it.  Without `where D: class` it needs the cast.  Why?  Strange. 

Good to know.  Thanks for the update.

But again PRs are welcome if you want to take a stab at fixing it.  The broken case works if you use your own extension methods.
