### ISSUE TITLE
UseAsDataSource with GroupBy

### ISSUE THREAD

**Issue by bizunas** [AutoMapper/AutoMapper.Extensions.ExpressionMapping#6]
AutoMapper: 7.0.1
AutoMapper.Extensions.ExpressionMapping: 1.0.2

I'm trying to make use of UseAsDataSource with GroupBy but it fails. Gist is here: [gist](https://gist.github.com/bizunas/d8e8e20530de32d8537988d1de3ee15b)
Where and OrderBy works like a charm. I have tried using GroupBy before UseAsDataSource with Entity objects, and it works. Is there a way to group data with UseAsDataSource ? 

Note: Adding `cfg.AddExpressionMapping();` does not help.

StackTrace: 
```
at System.ThrowHelper.ThrowWrongValueTypeArgumentException(Object value, Type targetType) 
at System.Collections.Generic.List`1.System.Collections.IList.Add(Object item) 
at AutoMapper.Extensions.ExpressionMapping.Impl.SourceInjectedQueryProvider`2.Execute[TResult](Expression expression) 
at AutoMapper.Extensions.ExpressionMapping.Impl.SourceSourceInjectedQuery`2.GetEnumerator()
at AutoMapper.Extensions.ExpressionMapping.Impl.SourceSourceInjectedQuery`2.System.Collections.IEnumerable.GetEnumerator()
at UserQuery.Main(String[] args)
--
```
Message: 
```
The value "System.Linq.Lookup`2+Grouping[System.Int32,UserQuery+Model]" is not of type "System.Linq.IGrouping`2[System.Int32,UserQuery+ModelDto]" and cannot be used in this generic collection.Parameter name: value
--
```

**Comment by BlaiseD** [comment]
I don't believe you can map IGroupings with AutoMapper.  Maybe figure out the result you need from the grouping and map the result e.g.:

```csharp
        public void Map_Group_by()
        {
            Mapper.Initialize(cfg =>
            {
                cfg.CreateMissingTypeMaps = true;
                cfg.ValidateInlineMaps = false;
                cfg.CreateMap<Model, ModelDto>();
            });

            System.Collections.Generic.List<Model> models = new List<Model> { new Model(), new Model() };
            System.Collections.Generic.IEnumerable<ModelDto> model2 = models.AsQueryable().DoQuery<ModelDto, Model, IEnumerable<ModelDto>, IEnumerable<Model>>(Mapper.Instance, q => q.GroupBy(x => x.Id).SelectMany(grp => grp.Select(z => z)));

        }

     public static class MyHelpers
    {
        internal static TModelResult DoQuery<TModel, TData, TModelResult, TDataResult>(this IQueryable<TData> query, IMapper mapper,
            Expression<Func<IQueryable<TModel>, TModelResult>> queryFunc)
        {
            //Map the expressions
            Func<IQueryable<TData>, TDataResult> mappedQueryFunc = mapper.MapExpression<Expression<Func<IQueryable<TData>, TDataResult>>>(queryFunc).Compile();

            //execute the query
            TDataResult res = mappedQueryFunc(query);
            
            //map and return
            return mapper.Map<TDataResult, TModelResult>(res);
        }
    }
```

UseAsDataSource may not be an option but PRs are welcome.

**Comment by TylerCarlson1** [comment]
It looks like grouping is not supported by `UseAsDataSource` as it is now.  It looks like it's not translating the model to dto in `IGrouping` generic types.

My best guess right now is it's translating the first generic argument `int` but not the second `ModelDto`.
`Where` `Select` and `OrderBy` have 1 generic type and that gets translated, or maybe it doesn't because it's usually `int` `string` or some anon type, but group by works differently because it has the dto object as generic argument and that scenario hasn't been accounted for.

**Comment by bizunas** [comment]
@BlaiseD Thank you for your answer, this approach works for my current situation.
