### ISSUE TITLE
UseAsDataSource OData expand trows Argument types do not match exception

### ISSUE THREAD

**Issue by mgdmiller** [AutoMapper/AutoMapper.Extensions.ExpressionMapping#60]
Hi!

I have simple project that uses odata. I decided to use an automapper because ist very simple. But i have problem with function _UseAsDataSource()_. When i use _ProjectTo()_ all work fine but EF cannot evaluate filter expressions in db and go it locally. But when i use _UseAsDataSource()_ its throw Argument types do not match exception when specifying $expand. I would like to use the functionality _UseAsDataSource()_ due to performance.

### Source/destination types

```csharp
// DB Objects below

public abstract class BaseDomainObject
{
	[Key]
	public long Id { get; set; }
}

public class Order : BaseDomainObject
{
	public virtual ICollection<OrderPosition> Positions { get;  } = new List<OrderPosition>();
}

public class OrderPosition : BaseDomainObject
{
	public virtual Order Order { get; set; }

	public int Amount { get; set; }
}

// DTO Objects below

public abstract class ApiModel
{
	public long Id { get; set; }
}

public class OrderModel : ApiModel
{
	public IEnumerable<OrderPositionModel> Positions { get; set; }
}

public class OrderPositionModel : ApiModel
{
	public int Amount { get; set; }
}

```

### Mapping configuration

```csharp
// Profile code

public class OrderProfile : Profile
{
	public OrderProfile()
	{
		CreateMap<BaseDomainObject, ApiModel>();
		CreateMap<Order, OrderModel>().IncludeBase<BaseDomainObject, ApiModel>();
		CreateMap<OrderPosition, OrderPositionModel>().IncludeBase<BaseDomainObject, ApiModel>();
	}
}
	
// Startup code
	
public void ConfigureServices(IServiceCollection services)
{
	services.AddDbContext<OrdersContext>(o =>
	{
		o.UseInMemoryDatabase("test");
		o.UseLazyLoadingProxies();
	});

	services.AddOData();
	services.AddAutoMapper( GetType());
	
	services.AddMvc(options => { options.EnableEndpointRouting = false; }).SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
}
```

### Expected behavior

Expected list expansion when specifying $expand=positions

### Actual behavior

Throws Argument types do not match

### Steps to reproduce

I create demonstration [project](https://github.com/mgdmiller/AutoMapperIssue)

```csharp
Simply call http://localhost:5000/api/orders?$expand=positions
```

Best regards. Vitaly

**Comment by lbargaoanu** [comment]
A PR is welcome.

**Comment by BlaiseD** [comment]
Have you considered the [OData Extensions library](https://github.com/AutoMapper/AutoMapper.Extensions.OData)?


Or creating your own mapping extensions like the [ReadMe](https://github.com/AutoMapper/AutoMapper.Extensions.ExpressionMapping) examples?

**Comment by mgdmiller** [comment]
> Have you considered the [OData Extensions library](https://github.com/AutoMapper/AutoMapper.Extensions.OData)?
> 
> Or creating your own mapping extensions like the [ReadMe](https://github.com/AutoMapper/AutoMapper.Extensions.ExpressionMapping) examples?

OData extensions work perfectly! I try to use _GetAsync_ method but it loading all set ignoring _PageSize_ controller option. But _GetQueryAsync_ works as it should. 

```csharp
[EnableQuery]
public async Task<IQueryable<TModel>> Get(ODataQueryOptions<TModel> options)
{
	return await _context.Set<TEntity>().GetQueryAsync(_mapper, options, HandleNullPropagationOption.False);
}
```
Thank you very much for your help!

**Comment by BlaiseD** [comment]
Sounds great.  Just FYI `EnableQuery` conflicts with the extension - you could be performing some operations twice.  The `EnableQuery` attribute should be removed.  Use `$top` for page size e.g. `http://localhost:1234/controller?$top=5`.

**Comment by mgdmiller** [comment]
Thanks for the clarification! I checked the behavior of _EnableQuery_, in my conditions it works correctly. The _TOP_ is not a hard limit, which can lead to fetching the entire table. But I will take this into account in the future!

**Comment by BlaiseD** [comment]
Just so other users get the correct information, **do not use the EnableQuery attribute with AutoMapper.Extensions.OData**.  See the [ReadMe](https://github.com/AutoMapper/AutoMapper.Extensions.OData) documentation and [issue #12 at AutoMapper.Extensions.OData](https://github.com/AutoMapper/AutoMapper.Extensions.OData/issues/12).  If we're missing a test case, please open an issue at [AutoMapper.Extensions.OData](https://github.com/AutoMapper/AutoMapper.Extensions.OData/issues).

**Comment by mgdmiller** [comment]
It is interesting.  I publish project to test environment and collect information for explain reply. It will take some time.
