### ISSUE TITLE
EFCore 3 OData filter with automapper throws client evaluation exception

### ISSUE THREAD

**Issue by isen-ng** [AutoMapper/AutoMapper.Extensions.ExpressionMapping#64]
EFCore 3.1
OData 7.3.0
Automapper 9.0.0
AutoMapper.Extensions.ExpressionMapping 3.1.0

I have a simple projection like this:

```c#
public class UserType {
   Human = 0,
   NonHuman = 1
}

// db model
public class User {
    public string Name { get; set; }
    public UserType UserType { get; set; }
}

// application model
public class UserDTO {
    public string Name { get; set ; }
    // for our business needs, this has to be a string, and not an enum
    public string UserType { get; set; } 
}
```

```c#
using AutoMapper;
public class AutoMapping : Profile
{
    public AutoMapping()
    {
        CreateMap<User, UserDTO>()
            .ForMember(dto => dto.UserType, opt => opt.MapFrom(db => db.UserType.ToString()));
    }
}
```

And then I have the query expression (created from OData)

```c#
    // this line of code does not really work, but it is just to illustrate a query generated from odata
    var dtoFilter = where<UserDTO>(dto => dto.UserType == "Human");

    // _mapper is injected
    var dbFilter = _mapper.MapExpression<Expression<Func<User, bool>>>(dtoFilter);

    query = query.where(dbFilter);
    return query.ToList();
```

This resulted in the following exception:

```
System.InvalidOperationException: The LINQ expression 'DbSet<User>
    .Where(m => m.UserType.ToString() == __TypedProperty_0)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|8_0(ShapedQueryExpression translated, <>c__DisplayClass8_0& )
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
 ...
```

I could reproduce exact error with the following linq query:

```c#
var result = _dbContext.Users
    .Where(x => x.UserType.ToString() == "Human")
    .ToListAsync().Result;
```

I could also fix the linq query by mapping the string parameter, instead of mapping the db paramter:

```c#
var result = _dbContext.Users
    .Where(x => x.UserType == Enum.Parse<UserType>("Human"))
    .ToListAsync().Result;
```

Is there something else I need to do to avoid this?

**Comment by isen-ng** [comment]
I have also tried adding a reverse mapping, but this results in the same exception as well.

```
using AutoMapper;
public class AutoMapping : Profile
{
    public AutoMapping()
    {
        CreateMap<User, UserDTO>()
            .ForMember(dto => dto.UserType, opt => opt.MapFrom(db => db.UserType.ToString()))
            .ReverseMap()
            .ForMember(db => db.UserType, opt => opt.MapFrom(dto => Enum.Parse<UserType>(dto.UserType)));
    }
}
```

**Comment by BlaiseD** [comment]
I wasn't able to reproduce this.  Look at [repository tests here](https://github.com/BlaiseD/LogicBuilder.DataComponents/blob/106deb9bee0c6a1751b4bfcfb2b97ee6c1f22bea/LogicBuilder.Kendo.ExpressionExtensions.IntegrationTests/RepositoryTests.cs#L71).

Add the following:
```c#
        [Fact]
        public void Get_enrollments_with_grade_a()
        {
            ISchoolRepository repository = serviceProvider.GetRequiredService<ISchoolRepository>();
            ICollection<EnrollmentModel> list = Task.Run(() => repository.GetItemsAsync<EnrollmentModel, Enrollment>(e => e.GradeLetter == "A")).Result;

            Assert.True(list.Count == 1);
        }
```
That worked for me (GradeLetter maps to a Grade enum type).


Should the following be a class or an enum?
```c#
public class UserType {
   Human = 0,
   NonHuman = 1
}
```
If "class" is not a typo then maybe that explains the exception.

Finally if `Enum.Parse` works in the filter then consider `x => Enum.GetName(typeof(UserType), x.UserType) == "Human"`.

You've proved it's an EF problem - producing the error outside AutoMapper but I was intrigued.

**Comment by isen-ng** [comment]
Hello!
Thank you for getting back to me and investigating! Yes, please pardon my typo. `UserType` should have been an enum, instead of a class.

Indeed, this is EFCore3 that is throwing the exception. However, it is expected that EFCore3 will throw that exception as this is already a warning when we were using EFCore2.2.

The exception is thrown because of how AutoMapper mapped the filter expression. It mapped the expression into:

```
DbSet<User>.Where(m => m.UserType.ToString() == __TypedProperty_0)
```

where `m.UserType.ToString()` is not translatable into server-side evaluatable filter. I am trying to find out how to configure (if possible) AutoMapper not to perform such mappings, but instead create a filter that will look like `m.UserType == __TypedProperty_0`, where `__TypedProperty_0` is an enum.


The integration test you linked looks interesting. Let's see if I can create a test that reproduces this issue.

**Comment by isen-ng** [comment]
Ohhhh, your integration tests have the profiles setup with the reverse map and all. 
I'll use that as an example to see if I can fix my code!

**Comment by isen-ng** [comment]
Hmm unfortunately, I have managed to reproduce the issue.
You integration tests pass because they are using an InMemoryDatabase. The moment I swap it out to an actual database, they query began to fail.

The same test that you gave in this thread:
https://github.com/isen-ng/LogicBuilder.DataComponents/blob/failing-test/LogicBuilder.Kendo.ExpressionExtensions.IntegrationTests/RepositoryTests.cs#L89

Setting up Postgres actual database:
https://github.com/isen-ng/LogicBuilder.DataComponents/blob/failing-test/LogicBuilder.Kendo.ExpressionExtensions.IntegrationTests/RepositoryTests.cs#L44

Use an actual database instead of an InMemoryDatabase:
https://github.com/isen-ng/LogicBuilder.DataComponents/blob/failing-test/LogicBuilder.Kendo.ExpressionExtensions.IntegrationTests/RepositoryTests.cs#L58

To run this test, you need to install docker.

**Comment by BlaiseD** [comment]
That definitely needs a solution.  I would open an issue [here](https://github.com/dotnet/efcore/issues).

There could be a solution using custom DbFunctions.

**Comment by isen-ng** [comment]
Out of curiosity, how did you arrive at the decision that this is a bug on the EFCore side of things instead of ExpressionMapper?

I'm not very well versed in EFCore history, so I'm not even sure of myself but, in my opinion, couldn't this be adjusted in automapper so that such expressions are not created?

**Comment by BlaiseD** [comment]
In one word: no.

- You can create the error without AutoMapper.  This blows up: `ICollection<Enrollment> list = context.Enrollments.Where(e => e.Grade.ToString() == "A").ToList();`.
- I won't necessarily call it a bug.  Going back to EF6 you couldn't do things like `x.Date.Today == someDateAt12am`.  A helper function like `TruncateTime(x.Date)` was necessary if my memory is correct. 

Define "such expressions".  ExpressionMapper's job is just that - mapping expressions.   EF translates expressions into SQL.  That's its job.

Different providers nHibernate, EFCore, EF6, MongoDb will have different capabilities.  

The solution (I don't have one yet) is to figure out an object mapping expression which EFCore can translate to SQL.

Make sense?

**Comment by isen-ng** [comment]
Ahh I think I get it now.

You're saying that in this situation, there is no way for ExpressionMapper to know that `where(dbModel.Grade.ToString() == "A")` is an offending filter. So there is no way for it to know that it should apply `where(dbModel.Grade == Enum.Parse<Grade>("A"))` instead.

(Oh I hate typing code on a mobile phone...)

**Comment by BlaiseD** [comment]
correct

**Comment by isen-ng** [comment]
@BlaiseD I've managed to raise the issue to an EFCore maintainer and basically he thinks that it is my responsibility that the odata filter query is not mapped into a query that offends the client-side evaluation rule. In my opinion, I do kinda agree with him.

https://github.com/npgsql/npgsql/issues/2885

**Comment by BlaiseD** [comment]
I think they are correct.

Really it should have been obvious to us because although EF uses enums in the model they are really mapped to INT types in the db. Then what could the generated SQL look like.  If we want this result:
`SELECT * FROM [Contoso].[dbo].[Enrollment] WHERE Grade = 0`

SQL Server can't convert grade to a string:
`SELECT * FROM [Contoso].[dbo].[Enrollment] WHERE ConvertMyIntFieldCalledGradeToWhatStringRepresentation = 'A'`

If you have control over your UserDto then you can fix the OData query to filter by enum e.g. take the tests [here](https://github.com/AutoMapper/AutoMapper.Extensions.OData/blob/45371f93c8928795befc6f32d9ee8f17881ca9e8/AutoMapper.OData.EFCore.Tests/AllTests.cs#L61).

Update the classes in DAL.EFCore and Domain.OData.
```c#
    public class TMandator
    {

        //existing

        public BuildingUseData BuildingUse { get; set; }

    }

    public enum BuildingUseData
    {
        Home,
        Business
    }

    public class OpsTenant
    {
        //existing
        public BuildingUseModel BuildingUse { get; set; }
    }

    public enum BuildingUseModel
    {
        Home,
        Business
    }
```
In Seed_Database:
```c#
            context.MandatorSet.Add(new TMandator
            {
                //existing
                BuildingUse = BuildingUseData.Home,
            });
            context.MandatorSet.Add(new TMandator
            {
                //existing
                BuildingUse = BuildingUseData.Business,
            });
```

Add the following test:
```c#
        [Fact]
        public async void OpsTenant_expand_Buildings_filter_by_enum_eq_and_order_by()
        {
            Test(await Get<OpsTenant, TMandator>("/opstenant?$top=5&$expand=Buildings&$filter=BuildingUse eq 'Business'&$orderby=Name desc"));

            void Test(ICollection<OpsTenant> collection)
            {
                Assert.True(collection.Count == 1);
                Assert.True(collection.First().Buildings.Count == 2);
                Assert.True(collection.First().Name == "Two");
            }
        }
```

This works.  I think the query needs an enum to do this - not a string.

**Comment by isen-ng** [comment]
Thank you @BlaiseD ! 
Really appreciate your efforts for helping me out this much!
I will try this out!

**Comment by BlaiseD** [comment]
np - like to be aware of all usage scenarios, what might not be feasible, and what can be done to fix/ compensate for/workaround problems.
