### ISSUE TITLE
CreateQuery(Expression expression) produces wrong ElementType for Select queries

### ISSUE THREAD

**Issue by mivor** [AutoMapper/AutoMapper.Extensions.ExpressionMapping#66]
Hi,

Automapper: 9.0.0
AutoMapper.Extensions.ExpressionMapping: 3.1.0

We ran into an issue with dynamically generated Select queries.
The non-generic `SourceInjectedQueryProvider.CreateQuery` always uses the original TDestination type and this leads problems when paired with Select. Because the ElementType of the query will remain the same.

https://github.com/AutoMapper/AutoMapper.Extensions.ExpressionMapping/blob/78f010b7c96c125bd6a8f6d930266cecf8c765db/src/AutoMapper.Extensions.ExpressionMapping/Impl/SourceInjectedQueryProvider.cs#L50-L51

For example instead of getting a list of Ids the result will be a list of DTOs with only the Id field populated.

I've looked into how other Queryables implement this and they take the generic type parameter of the given Expression as the Destination type.

I can create a PR with a fix if that's ok for you.

Here is a test with our use case to repro it:
``` c#
// Result will be
// Enumerable | Expected: System.Int32 Actual: System.Int32
// DataSource | Expected: System.Int32 Actual: Test.MappingTests+TestDto
    
    public class Test { public int Number { get; set; } }
    public class TestDto { public int Number { get; set; } }

    [TestMethod]
    public void QueryTest()
    {
      var config = new MapperConfiguration(c => c.CreateMap<Test, TestDto>());

      var query = new List<Test> {new Test {Number = 1}}.AsQueryable();
      var enumerable = query.Select(x => new TestDto { Number = x.Number }).AsQueryable();
      var dataSource = query.UseAsDataSource(config).For<TestDto>();

      CompareTypes(enumerable, "Enumerable");
      CompareTypes(dataSource, "DataSource");
    }

    private void CompareTypes(IQueryable<TestDto> source, string messge)
    {
      var regular = source.Select(x => x.Number);
      var manual = MakeSelect(source, "Number");

      Console.WriteLine($"{messge} | Expected: {regular.ElementType} Actual: {manual.ElementType}");
      Assert.AreEqual(regular.ElementType, manual.ElementType, messge);
    }

    private IQueryable MakeSelect(IQueryable source, string name)
    {
      var thisExpression = Expression.Parameter(source.ElementType, "");
      var prop = Expression.Property(thisExpression, name);
      var selector = Expression.Lambda(prop, thisExpression);

      var methodCallExpression = Expression.Call(
          typeof(Queryable),
          nameof(Queryable.Select),
          new [] {source.ElementType, selector.Body.Type}, 
          source.Expression, Expression.Quote(selector)
      );

      return source.Provider.CreateQuery(methodCallExpression);
    }
```

**Comment by BlaiseD** [comment]
I think you're comparing two things that do not represent the same thing:
```c#
            var enumerable = query.Select(x => new TestDto { Number = x.Number }).AsQueryable();
            var dataSource = query.UseAsDataSource(config).For<TestDto>();
            var dataSource2 = query.ProjectTo<TestDto>(config);
```
The first and the third do the same thing.  The 2nd one is different.  Plus in all three cases, `var list = regular.ToList();` returns a generic lit of Inst32. 

Not all the familiar with how `UseAsDataSource` works but it seems like it is working as designed.

**Comment by mivor** [comment]
The `regular` query is there for comparison.
The issue is with the `var manual = MakeSelect(source, "Number");` query.

Please run this code to see the difference:
``` C#
var selection = MakeSelect(dataSource, "Number");
Console.WriteLine($"ElementType: {selection.ElementType}");
foreach (var item in selection)
{
    Console.WriteLine($"Item Type: {item.GetType()}");
}
```

The result will be:
```
ElementType: MappingBug.Program+TestDto
Unhandled exception. System.InvalidOperationException: Missing map from System.Int32 to MappingBug.Program+TestDto. Create using CreateMap<Int32, TestDto>.
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpressionCore(ExpressionRequest request, Expression instanceParameter, IDictionary`2 typePairCount, LetPropertyMaps letPropertyMaps, TypeMap& typeMap)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpression(ExpressionRequest request, IDictionary`2 typePairCount, LetPropertyMaps letPropertyMaps)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpression(ExpressionRequest request)
   at AutoMapper.LockingConcurrentDictionary`2.<>c__DisplayClass2_1.<.ctor>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at AutoMapper.LockingConcurrentDictionary`2.GetOrAdd(TKey key)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.GetMapExpression(Type sourceType, Type destinationType, Object parameters, MemberInfo[] membersToExpand)
   at AutoMapper.Extensions.ExpressionMapping.Impl.SourceInjectedQueryProvider`2.Execute[TResult](Expression expression)
   at AutoMapper.Extensions.ExpressionMapping.Impl.SourceSourceInjectedQuery`2.GetEnumerator()
   at AutoMapper.Extensions.ExpressionMapping.Impl.SourceSourceInjectedQuery`2.System.Collections.IEnumerable.GetEnumerator()
```

The issue is that even tough the Select operator asks for an `int` the `ElementType` stays the same (`TestDto`). When executing it crashes because it tries to map the selected value of `int` to the `ElementType` of `TestDto`.

If I use any other `IQueryable` this sample works, but with `UseAsDataSource` it crashes.

**Comment by BlaiseD** [comment]
That's interesting.  You're creating a queryable using `UseAsDataSource` then modifying the queryable before hitting the database.

So e.g. this  `var dataSource = query.UseAsDataSource(config).For<TestDto>().ToList().AsQueryable();` works against `MakeSelect()` because the provider is different.

Go for it.

**Comment by BlaiseD** [comment]
A PR is welcome.  Also consider creating your own extension methods like implemented [here](https://github.com/AutoMapper/AutoMapper.Extensions.OData/blob/45371f93c8928795befc6f32d9ee8f17881ca9e8/AutoMapper.AspNetCore.OData.EFCore/QueryableExtensions.cs#L130).
