### ISSUE TITLE
Argument exception: Source and destination must have same number of arguments

### ISSUE THREAD

**Issue by Mytza** [AutoMapper/AutoMapper.Extensions.ExpressionMapping#8]
Hi,

I am upgrading from an old version of automapper (4.2.1) to latest. We had expression mapping in place between DTO and entities. I am now getting this exception when trying to map an expression from a dto that has extra collection properties that are not present on the entity.
This was working before upgrade.

Is it possible to handle this scenario like it was before. I looked over the source code and could not find any way to configure this.

Thanks in advance,
Mihai

**Comment by BlaiseD** [comment]
It's easier to help with a failing sample. Please include the smallest possible sample reproducing the error here, or as a gist or [here](https://github.com/Mytza?tab=repositories).

**Comment by Mytza** [comment]
Hi,

I have tried to make a new project and recreate the situation with a smaller number of mappings, and the expression mapping works even if i have an extra collection property on DTO. 
In my solution I am facing problems only with a single expression map concerning DTO to entity, the rest are working.

Maybe you can give me some hints what to look at, i am not sure what is causing the problem.

Regards,
Mihai

**Comment by BlaiseD** [comment]
We'll need to see the expression to helpful.  I would look at some of the [test cases](https://github.com/AutoMapper/AutoMapper.Extensions.ExpressionMapping/tree/master/tests/AutoMapper.Extensions.ExpressionMapping.UnitTests) as examples.  Show the source and destination objects with an expression reproducing the problem.

**Comment by artemvalmus** [comment]
Hi.

I faced the same issue. Please take a look at the example below:

References:
```
<PackageReference Include="AutoMapper" Version="7.0.1" />
<PackageReference Include="AutoMapper.Extensions.ExpressionMapping" Version="1.0.2" />
```
Console app:
```
namespace ConsoleApp
{
    class Program
    {
        class OrderModel
        {
            public IEnumerable<ItemModel> Items { get; set; }
        }

        class ItemModel
        {
            public string Name { get; set; }
        }

        class OrderEntity
        {
            public OrderData OrderData { get; set; }
        }

        class OrderData
        {
            public IEnumerable<ItemEntity> Items { get; set; }
        }

        class ItemEntity
        {
            public string Name { get; set; }
        }

        static void Main(string[] args)
        {
            var config = new MapperConfiguration(cfg => {
                cfg.CreateMap<OrderEntity, OrderModel>()
                    .ForMember(x => x.Items, opt => opt.MapFrom(x => x.OrderData.Items));
                cfg.CreateMap<ItemEntity, ItemModel>();

                cfg.AddExpressionMapping();
            });

            var mapper = config.CreateMapper();

            Expression<Func<OrderModel, bool>> src = x => x.Items.Any(i => i.Name == "Test");

            // exception: Source and destination must have the same number of arguments
            var dest = mapper.Map<Expression<Func<OrderEntity, bool>>>(src);

            Console.ReadKey();
        }
    }
}
```

**Comment by BlaiseD** [comment]
OK the bug is [here](https://github.com/AutoMapper/AutoMapper.Extensions.ExpressionMapping/blob/master/src/AutoMapper.Extensions.ExpressionMapping/MapperExtensions.cs#L293).  

Fix:
```c#
    if (pm.SourceMembers == null || pm.SourceMembers.Count() == 0)
        continue;
```
I'll open a PR. Thanks guys.
